/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
/* Header for class com_ram234_ramos_ndkopencvtest1_OpencvNativeClass */


using namespace cv;
using namespace std;

#ifndef _Included_com_ram234_ramos_ndkopencvtest1_OpencvNativeClass
#define _Included_com_ram234_ramos_ndkopencvtest1_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ram234_ramos_ndkopencvtest1_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */

 int toGray(Mat img, Mat& gray);

JNIEXPORT jint JNICALL Java_com_ram234_ramos_ndkopencvtest1_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
